name: neeleez_flutter_app
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
    sdk: '>=2.18.6 <3.0.0'
dependencies:
    flutter:
        sdk: flutter
    cupertino_icons: ^1.0.2
    http: ^0.13.5
    google_fonts: ^4.0.3
    get: ^4.6.5
    # sizer: ^2.0.15
    logger: ^1.3.0
    cached_network_image: ^3.2.3
    icons_launcher: ^2.1.0
    shared_preferences: ^2.0.18
    stacked: ^3.2.0
    responsive_builder: ^0.6.4
    provider: ^6.0.5
    get_it: ^7.2.0
    equatable: ^2.0.5
    page_transition: ^2.0.9
    country_code_picker: ^3.0.0
    fl_country_code_picker: ^0.1.2
    pinput: ^2.2.21
    shimmer: ^2.0.0
    dotted_border: ^2.0.0+3
    image_picker: ^0.8.7+4
    intl: ^0.17.0
    bot_toast: ^4.0.3
    file_picker: ^5.2.11
    geolocator: ^9.0.2
    path: ^1.8.2
    device_preview: ^1.1.0
    flutter_multi_formatter: ^2.11.0
    mask_text_input_formatter: ^2.4.0
    path_provider: ^2.0.15
    geocoding: ^2.1.0
    google_maps_flutter: ^2.2.8
    location: ^4.4.0
    flutter_map_location_marker: ^6.0.0
dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^2.0.0
flutter:
    generate: true
    uses-material-design: true
    assets:
        - assets/images/
        - assets/icons/


  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
      
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
      
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
      
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages